version: "3"
services:

  db:
    image: postgres:14.6-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=msghubdb
      - POSTGRES_PASSWORD=abgthgo

  api:
    build:
      context: .
    volumes: 
      - .:/msghub
    container_name: msghub_server_container
    env_file:
      - ./.env
    ports: 
      - 9000:9000
    depends_on:
      - db
    links:
      - db
